name: fractal-fireworks
services:
- name: web
  source_dir: /
  github:
    repo: tedo0626/fractal-fireworks
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /